git:
  baseurl: https://github.com
  prefix: QubesOS/qubes-
  branch: release4.2
  maintainers:
    # marmarek
    - '0064428F455451B3EBE78A7F063938BA42CFA724'
    # simon
    - '274E12AB03F2FE293765FC06DA0434BC706E1FCF'

backend-vmm: xen
debug: true
verbose: true
qubes-release: r4.3

distributions:
  - host-fc41

components:
  - zfs:
      url: https://github.com/aronowski/qubes-zfs-dkms
      branch: devel
      timeout: 21600
      maintainers:
        - 'FDCCF2DB25F9A7CE18D852DE2E26E3F5DA116A0E'


#executor:
#  type: docker
#  options:
#    image: "qubes-builder-fedora:latest"

executor:
  type: qubes
  options:
    dispvm: "@dispvm"

stages:
  - fetch
  - prep
  - build
  - post
  - verify
  - sign:
      executor:
        type: local
